
# Lab 2 – NumPy
---

NumPy is a library in Python for processing multi-dimensional arrays, along with a large collection of high-level mathematical functions to operate on these arrays.



In [ ]:
import numpy as np

print("Numpy:", np.__version__)

Numpy: 1.21.5


### Array creation

Create a simple scalar as an np array

In [ ]:
a = np.array(5)
print(a)
print(a.ndim)

5
0


Create a simple 1-D array


In [ ]:
a = np.array([0,1,2])
print(a)
print(a.ndim)
print(a.size)

[0 1 2]
1
3


Create a 1-D array with zeros in it

Check array properties

In [ ]:
a = np.zeros(3)
print(a)

# print array type
print(type(a))
# print array's first element
print(a[0])
# print type of array's first element
print(type(a[0]))
# print number of dimensions of array
print(a.ndim)
# print size of array
print(a.size)
# print array data type
print(a.dtype)

[0. 0. 0.]
<class 'numpy.ndarray'>
0.0
<class 'numpy.float64'>
1
3
float64


Specifying array data type

In [ ]:
a = np.array([1,2,3], dtype='int32')
print(a)
print(a.dtype)

[1 2 3]
int32


Create an array with 1's in it

In [ ]:
z = np.ones(10)
z

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Specying 2-D array data type


In [ ]:
z = np.ones((2,4), dtype=int) # Default dtype is numpy.float64
print(z)
print(z.dtype)

[[1 1 1 1]
 [1 1 1 1]]
int64


Fill array with a number

In [ ]:
np.full((3,4), 13)

array([[13, 13, 13, 13],
       [13, 13, 13, 13],
       [13, 13, 13, 13]])

### Identity matrix

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Array Shape

The shape of an array is the number of elements in each dimension.

In [ ]:
a = np.array([0,1,2,4,5,6,7,8])
print(a)
print(a.shape)

[0 1 2 4 5 6 7 8]
(8,)


Array rank is the number of dimensions

In [ ]:
print(a.ndim)

1


### Reshape
By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [ ]:
a.shape = (8,1)
print(a)

[[0]
 [1]
 [2]
 [4]
 [5]
 [6]
 [7]
 [8]]


Reshape from 1-D to 2-D

In [ ]:
b = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(b.ndim)
print(b.shape)
c = b.reshape(2,6)
print(c)
print(c.ndim)
print(c.shape)

1
(12,)
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
2
(2, 6)


Reshape to 3-D
- Arrays can be reshaped to any dimensions as long as the number of elements match


In [ ]:
d = c.reshape(2,3,2)
print(d)
d.shape

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


(2, 3, 2)

Unknown dimension

- You are allowed to have ONE "unknown" dimension *only*.
- Specify -1 for this, NumPy will calculate this number automatically.

In [ ]:
e = c.reshape(1,2,-1)
print(e)
print(e.shape)

[[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]]]
(1, 2, 6)


Reshape back to 1-D

In [ ]:
e = e.reshape(12)
print(e)
print(e.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


## Evenly spaced numbers over a specified number of elements or interval
- ``linspace()``
- ``arange()``


In [ ]:
z = np.linspace(2, 10, 5) # from 2 to 10 with 5 elements
z

array([ 2.,  4.,  6.,  8., 10.])

In [ ]:
z = np.arange(0, 10, step=5) # from 0 to 9 with step size 5
z

array([0, 5])

In [ ]:
z = np.arange(10)
z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


# NumPy Arrays vs Lists

*   Faster to read because it uses less bytes of memory via fixed type (e.g. Int32)
*   No type checking when iterating through objects
*   Utilises contiguous memory
*   Element wise operations possible


In [ ]:
# Create array from list
a = np.array([1,3,7])
print(a)
type(a)

[1 3 7]


numpy.ndarray

Convert array to list

In [ ]:
alist = np.ones(5).tolist()
print(alist)
type(alist)

[1.0, 1.0, 1.0, 1.0, 1.0]


list

## 2-D arrays

In [ ]:
alist = [[1,2,3,4], [8,7,6,5]]
z = np.array(alist)
print(z)
print(z.shape)

[[1 2 3 4]
 [8 7 6 5]]
(2, 4)


In [ ]:
blist = [[1,2,3,4], [8,7,6,5]]
z = np.array([blist])
print(z)
print(z.shape)

[[[1 2 3 4]
  [8 7 6 5]]]
(1, 2, 4)


## Random Array

Create a random integer array specifying range and size

In [ ]:
# random integers start, end exclusive, shape
np.random.randint(4,9,size=(3,4))

array([[4, 7, 4, 4],
       [5, 8, 6, 6],
       [8, 6, 6, 7]])

Create an array with 10 random numbers between 0 and 1

In [ ]:
np.random.random(10)

array([0.69592094, 0.01843122, 0.78644809, 0.14605127, 0.63751614,
       0.99001245, 0.98397007, 0.43221218, 0.64183531, 0.75217923])

Use seed() for reproducibility

In [ ]:
# Seed allows the random values generated will be the same every time the code is run
np.random.seed(0) # change 0 to any other integer value (e.g. 10) and see the effects
z1 = np.random.randint(10, size=6) # generate an array with 6 integers between 0 and 9
z1

array([5, 0, 3, 3, 7, 9])

## Basic operations

In [ ]:
z = np.array([1,2,3,8,9])
print(z<3)
z[z>3]

[ True  True False False False]


array([8, 9])

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a * 10)


[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[10 20 30 40 50]


## Dot product

In [ ]:
a @ b

130

## Transpose

Swap the rows and columns of an array

In [ ]:
c = np.array([[1,2,3], [4,5,6]])
c.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## Indexing & Slicing

- Remember indexes start at 0
- Accessing specific elements

In [ ]:
c = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])

# Index starts at 0
print(c[0,0])
print(c[1,2]) # row 1 (2nd row) , column 2 (3rd column)

1
10


## Slicing
- ``a[start:stop]``  # items ``start`` through ``stop-1``
- ``a[start:]``      # items ``start`` through the rest of the array
- ``a[:stop]``       # items from the beginning through ``stop-1``
- ``a[:]``           # a copy of the whole array


In [ ]:
# Get specific row/column
print(c[0, :]) # get row 0
print(c[ : ,2]) # get column 2
print(c[0,2:6])
print(c[ :1,2])
print(c.shape)

[1 2 3 4 5 6 7]
[ 3 10]
[3 4 5 6]
[3]
(2, 7)


### Indexing from the back
- ``a[-1]``    # last item in the array
- ``a[-2:]``   # last two items in the array
- ``a[:-2]``   # everything except the last two items
- Backward indexing starts from -1

In [ ]:
b = np.array([[9.0, 8.0, 7.0, 6.0], [5.0, 4.0, 3.0, 2.0]])
print(b[1,-2]) # starting indexing backwards (second element from the back)

3.0


### Including step
- ``a[start:stop:step]`` # ``start`` through not past ``stop``, by ``step``

In [ ]:
print(c[0,1:6:2])
print(c[1,1:-1:2])

[2 4 6]
[ 9 11 13]


### Changing elements

> Indented block



In [ ]:
c[1,5] = 20
print(c)

c[:, 2] = [17,19]
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2 17  4  5  6  7]
 [ 8  9 19 11 12 20 14]]


### Indexing 3-D arrays

In [ ]:
d = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
print(d)
print(d.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


In [ ]:
# Get specific element
print(d[0,1,1])

# All x, some y , all z
print(d[:,1,:])

9
[[9 9]
 [8 8]]


In [ ]:
# Replace
d[:,1,:] = [[9,9], [8,8]]
d

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

## Repeat array

In [ ]:
e = np.array([1,2,3])
np.repeat(e, 2)

array([1, 1, 2, 2, 3, 3])

In [ ]:
# repeat on an axis
e = np.array([[1,2,3]])
np.repeat(e, 2, axis=0)

array([[1, 2, 3],
       [1, 2, 3]])

In [ ]:
f = np.ones((5,5), dtype='int32')
f[1:-1, 1:-1] = 0
f[2,2] = 9
f

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

## Making copies


In [ ]:
g = np.array([1,2,3])
h = g # point h to g so they share content
h[1] = 100
print(g)

[  1 100   3]


In [ ]:
g = np.array([1,2,3])
h = g.copy() # explicitly make a copy
h[1] = 100
print(g)

[1 2 3]


# Linear Algebra

In [ ]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

# Statistics

In [ ]:
a = np.array([[1,2,3], [4,5,6]])
print(a.sum())
print(a.mean())
print(a.max())
print(a.min())
print(a.argmax())


21
3.5
6
1
5


Specifying axis
- Column: ``axis=0``
- Row: ``axis=1``

In [ ]:
print(np.min(a, axis=1)) # smallest values in rows
print(np.max(a, axis=0)) # largest values in columns

[1 4]
[4 5 6]


Others – Log and exponential

In [ ]:
print(np.log(a))
print(np.exp(a))

[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]
[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]


## Vertical stacking

In [ ]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

In [ ]:
np.hstack([v2,v1,v1])

array([5, 6, 7, 8, 1, 2, 3, 4, 1, 2, 3, 4])

In [ ]:
h1 = np.zeros((2,4))
h2 = np.ones((2,2))

np.hstack((h1,h2))

## Plotting with Matplotlib
- A simple example using post office international parcel charges for two countries

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

# Parcel weights start at 0.5kg to 20.5kgs in half kilo intervals
x = np.arange(0.5, 20.5, 0.5)

# Country 1 parcel charges
c1 = np.array([16.0, 19.0, 21.5, 24.5, 25.0, 27.3, 29.6, 31.9, 34.2, 36.5, 38.8, 41.1, 43.4, 45.7, 48.0, 50.3, 52.6, 54.9, 57.2, 59.5,
     61.8, 64.1, 66.4, 68.7, 71.0, 73.3, 75.6, 77.9, 80.2, 82.5, 84.8, 87.1, 89.4, 91.7, 94.0, 96.3, 98.6, 100.9, 103.2, 105.5])

# Country 2 parcel charges
c2 = np.array([16.0, 19.0, 21.5, 24.5, 25.5, 27.0, 28.5, 30.0, 31.5, 33, 34.5, 36, 37.5, 39, 40.5, 42, 43.5, 45, 46.5, 48,
     49.5, 51, 52.5, 54, 55.5, 57, 58.5, 60, 61.5, 63, 64.5, 66, 67.5, 69, 70.5, 72, 73.5, 75, 76.5, 78])

plt.plot(x,c1)
plt.plot(x,c2)
plt.xlabel("Weight (kg)")
plt.ylabel("Price (Thousand Won)")
plt.legend(['Country 1', 'Country 2'])
plt.show()

In [ ]:
# Get estimated value from plot using np.interp() for postal price for a weight that's not in the array
parcel_weight = 11.3 # change this to any other value and run again

est1 = np.interp(parcel_weight, x, c1)

est2 = np.interp(parcel_weight, x, c2)

print(f'Estimated parcel prices for weight {parcel_weight:.2f} is {est1} for Country 1 and {est2:.2f} for Country 2')