# Lab 2b – Tensors

In [ ]:
import torch

## Create empty tensors
- Uninitialised tensors

In [ ]:
# 1-D
x = torch.empty(1)
print(x)

# 1-D with two elements
x = torch.empty(2)
print(f"\n1-D tensor\n{x}\n")

# 2-D
x = torch.empty(2,3)
print(f"2-D tensor\n{x}\n")

# 3-D
x = torch.empty(2,3,1)
print("3-D tensor\n",x)


tensor([-1.6401e-37])

1-D tensor
tensor([-1.6259e-37,  3.0791e-41])

2-D tensor
tensor([[-1.6401e-37,  3.0791e-41,  3.3631e-44],
        [ 0.0000e+00,         nan,  1.9949e+00]])

3-D tensor
 tensor([[[-1.6259e-37],
         [ 3.0791e-41],
         [ 3.3631e-44]],

        [[ 0.0000e+00],
         [        nan],
         [ 1.9949e+00]]])


## Initialise tensors to scalar, random values, zeros or ones

In [ ]:
# 0-D tensor (just containing scalar value 3)
x = torch.tensor(3)
# print(x)
print(f'Scalar: {x} has shape {x.shape} and {x.ndim} dimensions\n')

# Random values in the interval [0,1]
x = torch.rand(2,3)
print(f"Random values:\n{x}")
print(x.dtype)

# Zeros
x = torch.zeros(2,3)
print(f"\nZeros:\n{x}")
print(x.dtype)

x = torch.zeros(2,3, dtype=torch.int)
print(f"\nZeros:\n{x}\n")

# Ones
x = torch.ones(2,3)
print(f"Ones:\n{x}")
print(f"Type: {x.dtype}\n")

x = torch.ones(2,3, dtype=torch.double)
print(f"Ones:\n{x}")

Scalar: 3 has shape torch.Size([]) and 0 dimensions

Random values:
tensor([[0.2667, 0.5231, 0.9295],
        [0.4766, 0.0537, 0.3231]])
torch.float32

Zeros:
tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.float32

Zeros:
tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

Ones:
tensor([[1., 1., 1.],
        [1., 1., 1.]])
Type: torch.float32

Ones:
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


## Construct tensor from data

In [ ]:
# Change a list to a tensor
x = torch.tensor([0.5, 2.7])
print(x)

tensor([0.5000, 2.7000])


### Changing tensor data type


In [ ]:
x = torch.rand(2,3) * 20
print(x)

# Change to integer
y = x.to(torch.int32)
print(y)

tensor([[ 2.9985, 18.1457, 17.7802],
        [18.5711, 13.8163, 14.4083]])
tensor([[ 2, 18, 17],
        [18, 13, 14]], dtype=torch.int32)


### Create a separate copy



In [ ]:
a = torch.ones(2, 2)
b = a.clone()

a[0][1] = 561          # a changes...
print(b)               # ...but b is still all ones

tensor([[1., 1.],
        [1., 1.]])


## Basic tensor operations

- addition, subtraction, multiplication, division

In [ ]:
x = torch.rand(2,2)
print(f"x = \n{x}\n")

y = torch.rand(2,2)
print(f"y = \n{y}\n")

z = torch.add(x,y) # same as z = x + y
print("x + y = ")
print(z)

z = torch.sub(x,y) # same as z = x - y
print("x - y = ")
print(z)

z = torch.mul(x,y) # same as z = x * y
print("x * y = ")
print(z)

z = torch.div(x,y) # same as z = x / y
print("x / y = ")
print(z)


x = 
tensor([[0.7858, 0.5064],
        [0.0930, 0.2930]])

y = 
tensor([[0.3747, 0.1130],
        [0.6210, 0.4242]])

x + y = 
tensor([[1.1604, 0.6194],
        [0.7139, 0.7172]])
x - y = 
tensor([[ 0.4111,  0.3934],
        [-0.5280, -0.1312]])
x * y = 
tensor([[0.2944, 0.0572],
        [0.0577, 0.1243]])
x / y = 
tensor([[2.0973, 4.4814],
        [0.1497, 0.6908]])


### Inplace operations

- any function with a trailing underscore (e.g. ``add_``) will modify the value of the variable in question, in place

In [ ]:
x = torch.rand(2,2)
print(f"x = \n{x}\n")

y = torch.rand(2,2)
print(f"y = \n{y}\n")

# Inplace operations
y.add_(x) # modify y by adding x to it
print(f"y + x = {y}")

y.sub_(x) # modify y by subtracting x from it
print(f"y - x = {y}")

y.mul_(x) # modify y by multiplying x to it
print(f"y * x = {y}")

y.div_(x) # modify y by dividing it by x
print(f"y / x = {y}")


x = 
tensor([[0.4521, 0.2949],
        [0.7771, 0.5354]])

y = 
tensor([[0.0011, 0.9382],
        [0.4458, 0.9125]])

y + x = tensor([[0.4532, 1.2332],
        [1.2229, 1.4479]])
y - x = tensor([[0.0011, 0.9382],
        [0.4458, 0.9125]])
y * x = tensor([[0.0005, 0.2767],
        [0.3464, 0.4886]])
y / x = tensor([[0.0011, 0.9382],
        [0.4458, 0.9125]])


## Accessing tensors

In [ ]:
# Slicing
x = torch.rand(5,3)
print(x)

# Get all rows but only first column
print(x[:, 0])

# Get all columns but only the second row
print(x[1, :])

# Get a specific element
print(x[2,2])

# When the tensor returns only ONE element, use item() to get the actual value of that element
print(x[1,1].item())

y = torch.tensor([2.0])
print(y.item())

tensor([[0.7310, 0.3909, 0.3493],
        [0.9103, 0.1685, 0.5225],
        [0.4148, 0.5326, 0.7712],
        [0.5663, 0.7637, 0.6158],
        [0.6644, 0.2525, 0.1158]])
tensor([0.7310, 0.9103, 0.4148, 0.5663, 0.6644])
tensor([0.9103, 0.1685, 0.5225])
tensor(0.7712)
0.16850602626800537
2.0


## Tensor Shape & Dimensions
- The number of dimensions a tensor has is called its rank and the length in each dimension describes its ``shape``.
- To determine the length of each dimension, call ``.shape``
- To determine the number of dimensions it has, call ``.ndim``


In [ ]:
x = torch.rand(5,3)
print(f'{x} \nhas shape {x.shape} and {x.ndim} dimensions\n')

tensor([[0.8992, 0.5299, 0.7389],
        [0.7867, 0.4671, 0.9290],
        [0.1777, 0.9392, 0.8838],
        [0.4486, 0.8492, 0.2445],
        [0.3936, 0.7522, 0.0349]]) 
has shape torch.Size([5, 3]) and 2 dimensions



## More on Shapes

- `[1,5,2,6]` has shape (4,) to indicate it has 4 elements and the missing element after the comma means it is a 1-D tensor or array (vector)
- `[[1,5,2,6], [1,2,3,1]]` has shape (2,4) to indicate it has 2 elements (rows) and each of these have 4 elements (columns). This is a 2-D tensor or array (matrix or a list of vectors)
- `[[[1,5,2,6], [1,2,3,1]], [[5,2,1,2], [6,4,3,2]], [[7,8,5,3], [2,2,9,6]]]` has shape (3, 2, 4) to indicate it has 3 elements in the first dimension, and each of these contain 2 elements and each of these contain 4 elements. This is a 3-D tensor or array


## Operations on tensor dimensions
- A tensor dimension is akin to an array's axis. The number of dimensions is called rank.
- A scalar has rank 0, a vector has rank 1, a matrix has rank 2, a cuboid has rank 3, etc.
- Sometimes one wants to do an operation only on a particular dimension, e.g. on the rows only
- Across ``dim=X`` means we do the operation w.r.t to the dimension given and the rest of the dimensions of the tensor stays as they are
- in 2-D tensors, ``dim=0`` refers to the columns while ``dim=1`` refers to the rows


In [ ]:
x = torch.tensor([[1,2,3],
                 [4,5,6]])

print(x.shape)
print(f'Summing across dim=0 (columns) gives: {torch.sum(x,dim=0)}')

print(f'Summing across dim=1 (rows) gives: {torch.sum(x,dim=1)}')


torch.Size([2, 3])
Summing across dim=0 (columns) gives: tensor([5, 7, 9])
Summing across dim=1 (rows) gives: tensor([ 6, 15])


## Reshaping tensors
- There are several ways to do this but using ``torch.reshape()`` is the most common
- Also look up ``torch.squeeze(), torch.unsqueeze()`` and ``torch.view()``


In [ ]:
x = torch.rand(4,4)
print("Original:")
print(x)
print(x.shape)

# Reshape (flatten) to 1-D
y = x.reshape(16) # number of elements must be the same as original, error otherwise
print("Reshaped to 1-D:")
print(y)

# Reshape to 2-D
y = x.reshape(8,2)
print("Reshaped to 2-D:")
print(y)

# Could leave out one of the dimensions by specifying -1
y = x.reshape(2, -1)
print("Reshaped to 2 x Unspecified 2-D:")
print(y)
print(y.shape)

# Could use unsqueeze(0) to add a dimension at position 0
y = x.unsqueeze(0)
print(f'Using unsqueeze(0) to add dimension from original shape {x.shape} to {y.shape}')

Original:
tensor([[0.7476, 0.0700, 0.9289, 0.3911],
        [0.7733, 0.1971, 0.6914, 0.7476],
        [0.7555, 0.3965, 0.4715, 0.0777],
        [0.0822, 0.4773, 0.8348, 0.1061]])
torch.Size([4, 4])
Reshaped to 1-D:
tensor([0.7476, 0.0700, 0.9289, 0.3911, 0.7733, 0.1971, 0.6914, 0.7476, 0.7555,
        0.3965, 0.4715, 0.0777, 0.0822, 0.4773, 0.8348, 0.1061])
Reshaped to 2-D:
tensor([[0.7476, 0.0700],
        [0.9289, 0.3911],
        [0.7733, 0.1971],
        [0.6914, 0.7476],
        [0.7555, 0.3965],
        [0.4715, 0.0777],
        [0.0822, 0.4773],
        [0.8348, 0.1061]])
Reshaped to 2 x Unspecified 2-D:
tensor([[0.7476, 0.0700, 0.9289, 0.3911, 0.7733, 0.1971, 0.6914, 0.7476],
        [0.7555, 0.3965, 0.4715, 0.0777, 0.0822, 0.4773, 0.8348, 0.1061]])
torch.Size([2, 8])
Using unsqueeze(0) to add dimension from original shape torch.Size([4, 4]) to torch.Size([1, 4, 4])


## Convert between NumPy and PyTorch tensors

- Tensors can work on CPUs and GPUs
- NumPy arrays can only work on CPUs

In [ ]:
import torch
import numpy as np

# Tensor to NumPy
a = torch.ones(5)
print(a)

b = a.numpy()
print(b)
print(type(b))

# b changes when a is modified because they share the same memory space!
a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [ ]:
import torch
import numpy as np

a = np.ones(5)
print(a)

b = torch.from_numpy(a)
print(b)

# Modifying array will modify the tensor as well
a += 2
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[3. 3. 3. 3. 3.]
tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


# Exercise

In [ ]:
# 1. Create a tensor of 100 equally spaced numbers from 0 to 2.
# Assign the tensor to x (Hint: use torch.linspace() )

x = torch.linspace(0,2,100)

# Print x

print(f"x = {x}")


x = tensor([0.0000, 0.0202, 0.0404, 0.0606, 0.0808, 0.1010, 0.1212, 0.1414, 0.1616,
        0.1818, 0.2020, 0.2222, 0.2424, 0.2626, 0.2828, 0.3030, 0.3232, 0.3434,
        0.3636, 0.3838, 0.4040, 0.4242, 0.4444, 0.4646, 0.4848, 0.5051, 0.5253,
        0.5455, 0.5657, 0.5859, 0.6061, 0.6263, 0.6465, 0.6667, 0.6869, 0.7071,
        0.7273, 0.7475, 0.7677, 0.7879, 0.8081, 0.8283, 0.8485, 0.8687, 0.8889,
        0.9091, 0.9293, 0.9495, 0.9697, 0.9899, 1.0101, 1.0303, 1.0505, 1.0707,
        1.0909, 1.1111, 1.1313, 1.1515, 1.1717, 1.1919, 1.2121, 1.2323, 1.2525,
        1.2727, 1.2929, 1.3131, 1.3333, 1.3535, 1.3737, 1.3939, 1.4141, 1.4343,
        1.4545, 1.4747, 1.4949, 1.5152, 1.5354, 1.5556, 1.5758, 1.5960, 1.6162,
        1.6364, 1.6566, 1.6768, 1.6970, 1.7172, 1.7374, 1.7576, 1.7778, 1.7980,
        1.8182, 1.8384, 1.8586, 1.8788, 1.8990, 1.9192, 1.9394, 1.9596, 1.9798,
        2.0000])


In [ ]:
# 3. Print the first 5 numbers in x.
print(f"First 5 numbers in x: \n{x[0:4]}\n")

# 4. Print the last 5 numbers in x
print(f"Last 5 numbers in x: \n{x[95:100]}")

First 5 numbers in x: 
tensor([0.0000, 0.0202, 0.0404, 0.0606])

Last 5 numbers in x: 
tensor([1.9192, 1.9394, 1.9596, 1.9798, 2.0000])


In [ ]:
# 5. Create another tensor of 100 random values between 0 and 1.
# Assign the tensor to y (Hint: use torch.rand() )
y = torch.rand(1,100)

# y = torch.rand(10,10)
# need to reshape x as a 10 * 10 to calc z
# x = x.reshape(10,10)

# Print y
print(f"y = {y}")

y = tensor([[0.6187, 0.7787, 0.1163, 0.3768, 0.0322, 0.0910, 0.2454, 0.9379, 0.3906,
         0.2919, 0.4019, 0.1066, 0.1179, 0.9111, 0.3442, 0.5851, 0.6848, 0.8238,
         0.4880, 0.9914, 0.3723, 0.9521, 0.7832, 0.4186, 0.5874, 0.4758, 0.0329,
         0.2289, 0.3470, 0.4453, 0.5716, 0.9835, 0.9931, 0.5627, 0.1921, 0.9413,
         0.9553, 0.9310, 0.2563, 0.3182, 0.7996, 0.6896, 0.7640, 0.8196, 0.4438,
         0.9120, 0.0032, 0.2680, 0.7992, 0.4466, 0.5117, 0.6615, 0.8342, 0.1997,
         0.0992, 0.9067, 0.7851, 0.1470, 0.1613, 0.2392, 0.5321, 0.2475, 0.4714,
         0.1302, 0.0013, 0.0509, 0.6915, 0.2199, 0.8074, 0.1740, 0.6018, 0.9649,
         0.0989, 0.8968, 0.7255, 0.1544, 0.5259, 0.0840, 0.2019, 0.7658, 0.3405,
         0.3112, 0.1003, 0.6830, 0.4766, 0.4102, 0.6371, 0.4683, 0.9571, 0.1668,
         0.2395, 0.5042, 0.6865, 0.4143, 0.3342, 0.2388, 0.8642, 0.8660, 0.6926,
         0.6861]])


In [ ]:
# 6. Multiply x and y, store the result in z
z = torch.mul(x,y)

# Print z
print(f"x * y = \n{z}")

x * y = 
tensor([[0.0000, 0.0157, 0.0047, 0.0228, 0.0026, 0.0092, 0.0297, 0.1326, 0.0631,
         0.0531, 0.0812, 0.0237, 0.0286, 0.2393, 0.0973, 0.1773, 0.2214, 0.2829,
         0.1774, 0.3805, 0.1504, 0.4039, 0.3481, 0.1945, 0.2848, 0.2403, 0.0173,
         0.1248, 0.1963, 0.2609, 0.3464, 0.6159, 0.6420, 0.3751, 0.1319, 0.6656,
         0.6947, 0.6959, 0.1967, 0.2507, 0.6461, 0.5712, 0.6483, 0.7120, 0.3945,
         0.8291, 0.0030, 0.2544, 0.7750, 0.4421, 0.5169, 0.6815, 0.8764, 0.2138,
         0.1082, 1.0075, 0.8882, 0.1692, 0.1890, 0.2851, 0.6449, 0.3050, 0.5905,
         0.1657, 0.0017, 0.0668, 0.9220, 0.2976, 1.1091, 0.2425, 0.8510, 1.3840,
         0.1439, 1.3226, 1.0845, 0.2339, 0.8074, 0.1306, 0.3181, 1.2221, 0.5504,
         0.5093, 0.1662, 1.1452, 0.8088, 0.7044, 1.1069, 0.8231, 1.7016, 0.3000,
         0.4354, 0.9269, 1.2759, 0.7784, 0.6346, 0.4582, 1.6759, 1.6971, 1.3711,
         1.3723]])


In [ ]:
# 7. Reshape z to a tensor with 5 rows and 20 columns
# Store reshaped tensor to z2
z2 = z.reshape(5,20)

# Print z2
print(f"Reshaped as a 2D tensor with {z2.shape}: \n{z2}")

Reshaped as a 2D tensor with torch.Size([5, 20]): 
tensor([[0.0000, 0.0157, 0.0047, 0.0228, 0.0026, 0.0092, 0.0297, 0.1326, 0.0631,
         0.0531, 0.0812, 0.0237, 0.0286, 0.2393, 0.0973, 0.1773, 0.2214, 0.2829,
         0.1774, 0.3805],
        [0.1504, 0.4039, 0.3481, 0.1945, 0.2848, 0.2403, 0.0173, 0.1248, 0.1963,
         0.2609, 0.3464, 0.6159, 0.6420, 0.3751, 0.1319, 0.6656, 0.6947, 0.6959,
         0.1967, 0.2507],
        [0.6461, 0.5712, 0.6483, 0.7120, 0.3945, 0.8291, 0.0030, 0.2544, 0.7750,
         0.4421, 0.5169, 0.6815, 0.8764, 0.2138, 0.1082, 1.0075, 0.8882, 0.1692,
         0.1890, 0.2851],
        [0.6449, 0.3050, 0.5905, 0.1657, 0.0017, 0.0668, 0.9220, 0.2976, 1.1091,
         0.2425, 0.8510, 1.3840, 0.1439, 1.3226, 1.0845, 0.2339, 0.8074, 0.1306,
         0.3181, 1.2221],
        [0.5504, 0.5093, 0.1662, 1.1452, 0.8088, 0.7044, 1.1069, 0.8231, 1.7016,
         0.3000, 0.4354, 0.9269, 1.2759, 0.7784, 0.6346, 0.4582, 1.6759, 1.6971,
         1.3711, 1.3723]])


In [ ]:
# 8. Get the sum of each row in z2
# check: should only get 5 numbers since there are 5 rows
print(f"Sum of each row in z2: \n{torch.sum(z2, dim = 1)}\n")

# 9. Get the mean of each column in z2
# check: should get 20 numbers since there are 20 columns
print(f"Mean of each column in z2: \n{torch.mean(z2, dim = 0)}")

Sum of each row in z2: 
tensor([ 2.0433,  6.8363, 10.2114, 11.8440, 18.4417])

Mean of each column in z2: 
tensor([0.3984, 0.3610, 0.3515, 0.4480, 0.2985, 0.3700, 0.4158, 0.3265, 0.7690,
        0.2597, 0.4462, 0.7264, 0.5933, 0.5859, 0.4113, 0.5085, 0.8575, 0.5951,
        0.4505, 0.7021])


In [ ]:
# 10. Reshape z to a 3D tensor (keep all the elements)
# Store reshaped tensor to z3
z3 = z.reshape(5,2,10)

# Print z3
print(f"Reshaped as a 3D tensor: \n{z3}")

# z3 = z.reshape(5, 5, -1)
# print(z3)

Reshaped as a 3D tensor: 
tensor([[[0.0000, 0.0157, 0.0047, 0.0228, 0.0026, 0.0092, 0.0297, 0.1326,
          0.0631, 0.0531],
         [0.0812, 0.0237, 0.0286, 0.2393, 0.0973, 0.1773, 0.2214, 0.2829,
          0.1774, 0.3805]],

        [[0.1504, 0.4039, 0.3481, 0.1945, 0.2848, 0.2403, 0.0173, 0.1248,
          0.1963, 0.2609],
         [0.3464, 0.6159, 0.6420, 0.3751, 0.1319, 0.6656, 0.6947, 0.6959,
          0.1967, 0.2507]],

        [[0.6461, 0.5712, 0.6483, 0.7120, 0.3945, 0.8291, 0.0030, 0.2544,
          0.7750, 0.4421],
         [0.5169, 0.6815, 0.8764, 0.2138, 0.1082, 1.0075, 0.8882, 0.1692,
          0.1890, 0.2851]],

        [[0.6449, 0.3050, 0.5905, 0.1657, 0.0017, 0.0668, 0.9220, 0.2976,
          1.1091, 0.2425],
         [0.8510, 1.3840, 0.1439, 1.3226, 1.0845, 0.2339, 0.8074, 0.1306,
          0.3181, 1.2221]],

        [[0.5504, 0.5093, 0.1662, 1.1452, 0.8088, 0.7044, 1.1069, 0.8231,
          1.7016, 0.3000],
         [0.4354, 0.9269, 1.2759, 0.7784, 0.6346, 0.4582,